[package]
name = "rustradio"
version = "0.0.1"
authors = ["Allen Welkie <allen.welkie is my gmail>"]

[dependencies.num]
git = "https://github.com/rust-lang/num"

[dependencies.IteratorExtras]
git = "https://github.com/awelkie/IteratorExtras"
